#!/usr/bin/env node
// Generate src/app/tokens.css from src/design/tokens.json (DTCG 2025.10).
// Source of truth is frontend/DESIGN.md; tokens.json is the @google/design.md
// DTCG export of it. This script renders the DTCG payload as a Tailwind v4
// `@theme` block so utilities like `bg-primary`, `text-foreground`,
// `rounded-sm`, `font-h2`, `text-body` are generated by Tailwind.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, "..");
const SRC = join(ROOT, "src/design/tokens.json");
const DEST = join(ROOT, "src/app/tokens.css");

const tokens = JSON.parse(readFileSync(SRC, "utf8"));

const lines = [
  "/* Generated from frontend/DESIGN.md via scripts/generate-tokens.mjs — do not edit by hand. */",
  "",
  "@theme {",
];

const entries = (group) =>
  Object.entries(group ?? {}).filter(([key]) => !key.startsWith("$"));

lines.push("  /* Colors */");
for (const [name, token] of entries(tokens.color)) {
  lines.push(`  --color-${name}: ${token.$value.hex};`);
}
lines.push("");

lines.push("  /* Spacing */");
for (const [name, token] of entries(tokens.spacing)) {
  const { value, unit } = token.$value;
  lines.push(`  --spacing-${name}: ${value}${unit};`);
}
lines.push("");

lines.push("  /* Radius */");
for (const [name, token] of entries(tokens.rounded)) {
  const { value, unit } = token.$value;
  lines.push(`  --radius-${name}: ${value}${unit};`);
}
lines.push("");

const FALLBACKS = {
  Aleo: "serif",
  Rubik: "sans-serif",
  "Fira Code": "monospace",
};

lines.push("  /* Typography (families) */");
for (const [name, token] of entries(tokens.typography)) {
  const family = token.$value.fontFamily;
  const fallback = FALLBACKS[family] ?? "sans-serif";
  lines.push(`  --font-${name}: "${family}", ${fallback};`);
}
lines.push("");

lines.push("  /* Typography (sizes & metrics) */");
for (const [name, token] of entries(tokens.typography)) {
  const v = token.$value;
  lines.push(`  --text-${name}: ${v.fontSize.value}${v.fontSize.unit};`);
  if (v.fontWeight) {
    lines.push(`  --text-${name}--font-weight: ${v.fontWeight};`);
  }
  if (v.letterSpacing) {
    lines.push(
      `  --text-${name}--letter-spacing: ${v.letterSpacing.value}${v.letterSpacing.unit};`
    );
  }
}

lines.push("}", "");

writeFileSync(DEST, lines.join("\n"));
console.log(`Wrote ${DEST}`);